In [ ]:
import numpy as np

In [ ]:
print(np.sqrt(49))
print(np.cos(np.pi))
print(np.log(np.exp(5.2)))

7.0
-1.0
5.2


In [ ]:
vec = np.array([1,2,4])
print(vec);
vec2 = np.arange(0,15); #second parameter is exclusive
print(vec2);
vec3 = np.arange(0,25,5);
print(vec3);

[1 2 4]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  5 10 15 20]


In [ ]:
vec4 = np.linspace(0,5,10);
print(vec4);
print('');
print(vec4.reshape(5,2));
print(vec4);

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [ ]:
mat = np.zeros([5,3])
print(mat);
mat1 = np.ones([2,5]);
print(mat1);
mat2 = np.eye(3);
print(mat2);

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
mat_sam = np.array([[1,2,1],[4,5,6],[1,8,9]]);
vec_sam = np.array([3,7,8]);
product = np.matmul(mat_sam,vec_sam);
print(product);

print(np.linalg.solve(mat_sam,product));
print(np.linalg.inv(mat_sam));

[ 25  95 131]
[3. 7. 8.]
[[ 0.08333333  0.27777778 -0.19444444]
 [ 0.83333333 -0.22222222  0.05555556]
 [-0.75        0.16666667  0.08333333]]


In [ ]:
vec7 = np.array(['red','Red','ora','ora',0]);
print(np.unique(vec7));

['0' 'Red' 'ora' 'red']


In [ ]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.16438885 0.02703606 0.96542054 0.39381875 0.99992171]
 [0.90287292 0.31795938 0.28436322 0.6403563  0.91505209]
 [0.0573794  0.46146127 0.71273656 0.13647697 0.3171007 ]
 [0.52250395 0.20018831 0.5710396  0.81776118 0.19160986]
 [0.45469214 0.70481455 0.6141179  0.39484144 0.5033264 ]]

[[ 1.845209    0.94599163 -0.24029901 -0.37785569 -1.34613814]
 [-0.21354864 -0.11117267 -1.9547939   0.68900524  0.10228202]
 [-0.40757665  0.09348776  0.0064106   0.00385364  0.34262902]
 [-0.54877896  1.4633181  -1.34781049 -0.04657695  0.15002806]
 [ 0.76651906  1.9198152  -1.54528113  0.99531002 -0.60109994]
 [ 2.29733279 -0.44399406 -1.73575936  1.59252346  0.65575884]
 [-1.35216367  2.17145922 -1.33845508 -0.14590567 -1.13320894]
 [ 0.65922671  0.69479363 -0.49944282  1.06100282 -0.36624368]
 [-1.13338002 -0.24332884  1.08493361 -0.00867568  0.51924546]
 [ 1.03361033 -0.51294244 -1.31508677  0.79283171  0.64625484]]


Collections

 1) List - Collection of objects surrounded by "[ ]"

 2) Tuple - similar to list but this is immutable. Represented by "(  )"

 3)  Set - unordered List and does not allow duplicates and represented by "{  }"

 4) Dictionary - Key Value pair

In [ ]:
alist = ["python", 2.1, 1,"Gayu", 6];
print(alist);
print(alist[0]);
print(alist[-1]);
alist[2] = 3;
print(alist);
alist.append("to the back");
print(alist);
alist.pop();
print(alist);

['python', 2.1, 1, 'Gayu', 6]
python
6
['python', 2.1, 3, 'Gayu', 6]
['python', 2.1, 3, 'Gayu', 6, 'to the back']
['python', 2.1, 3, 'Gayu', 6]


In [ ]:
#Initialize list with all same element for n size
list1 = [5]*4;
print(list1);

[5, 5, 5, 5]


In [ ]:
#we can use list as entries of list
alist[1] = [1,2,4];
print(alist);
print(alist[1][1]);

['python', [1, 2, 4], 3, 'Gayu', 6]
2


In [ ]:
#copying the list. Simply assigning the list to another variable shares same memory/reference.
copy_list = alist;
print(alist);
print(copy_list);
print("-------------");
copy_list[1] = 2.1;
print(alist);
print(copy_list);
print("------------");
copy_list = alist.copy();
copy_list[1] =  [1,2,4];
print(alist);
print(copy_list);

['python', [1, 2, 4], 3, 'Gayu', 6]
['python', [1, 2, 4], 3, 'Gayu', 6]
-------------
['python', 2.1, 3, 'Gayu', 6]
['python', 2.1, 3, 'Gayu', 6]
------------
['python', 2.1, 3, 'Gayu', 6]
['python', [1, 2, 4], 3, 'Gayu', 6]


In [ ]:
atuple = (1, 233,233, 13, 11);
print(atuple);
print(atuple[1]);
# this will not work !! tuple[1] = 11;
# work around - convert tuple to list
tuple_list = list(atuple);
tuple_list[1] = 100;
print(tuple_list);


(1, 233, 233, 13, 11)
233
[1, 100, 233, 13, 11]


In [ ]:
aSet = {1,2,3,1};
print(aSet);
#print(aSet[1]); # throws error --  as they are unordered
print(2 in aSet);

aSet.add("water");
aSet.remove(2);
print(aSet);

{1, 2, 3}
True
{1, 3, 'water'}


In [ ]:
aDict = {
    "name" : "Gayathri",
    "phone" :"Realme",
    "age" : 27
};
print(aDict);
print(aDict["name"]);
aDict["phone"] = "Samsung";
aDict["country"] = "USA";
print(aDict);

{'name': 'Gayathri', 'phone': 'Realme', 'age': 27}
Gayathri
{'name': 'Gayathri', 'phone': 'Samsung', 'age': 27, 'country': 'USA'}


In [ ]:
#Accessing data in list
list_sample = [1,4,64,22,34,23];
print(list_sample[2:5]);
print(list_sample[2:3]);
print(list_sample[-3:-1]);

[64, 22, 34]
[64]
[22, 34]
