<a href="https://colab.research.google.com/github/GayathriRenganathan/python/blob/master/Copy_of_Python_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Multiline Commenting with """"""
"""multiple line
commented"""

In [0]:
import numpy as np
from scipy import stats
ages = [10,15,11,11,23,34,96]

print("mean {}".format(np.mean(ages)))
print("median {}".format(np.median(ages)))
print("mode {}".format(stats.mode(ages).mode))


mean 28.571428571428573
median 15.0
mode [11]


In [0]:
import seaborn as sns

iris = sns.load_dataset('iris')

iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [0]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
print(A)
'''Ravel flattens the array . By default it is row wise which is C
F is column wise, A is memory reference wise, '''
print (A.ravel())
print(A.ravel(order = 'F'))

print(A.ravel(order = 'C'))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 4 2 5 3 6]
[1 2 3 4 5 6]


In [0]:
b =  np.array([[1,2,3],[4,5,6]])
print(b)

print(b.reshape(3,2,order = 'C'))

c = np.arange(8)
print(c)

print(c.reshape(2,4,order = 'F'))

d = np.array([[1,2,3,4],[5,6,7,8]])
print(d)
print(d.reshape(4,2,order = 'F'))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[0 1 2 3 4 5 6 7]
[[0 2 4 6]
 [1 3 5 7]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 3]
 [5 7]
 [2 4]
 [6 8]]


In [0]:
word = "I love python "
word[7:13]

'python'

In [0]:
d = {0, 1, 2}
for x in d:
    print(d.add(x))

None
None
None


In [0]:
print([i+j for i in "abc" for j in "def"])

['ad', 'ae', 'af', 'bd', 'be', 'bf', 'cd', 'ce', 'cf']


In [0]:
d = {x.upper(): x*3 for x in 'acbd'}
print(d)

{'A': 'aaa', 'C': 'ccc', 'B': 'bbb', 'D': 'ddd'}


In [0]:
min = (lambda x, y: x if x < y else y)
min(101*99, 102*98)

9996